package:
    name: pyg-encoders
    version: 0.0.10

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - pyg-base          >=0.0.19
        - pyg-npy           >=0.0.7
    run:
        - pyg-base          >=0.0.17
        - pyg-npy           >=0.0.7
        
about:
    home: https://github.com/gityoav/pyg-encoders
    license: GNU